import math
from typing import Callable, Generator
from numba import njit, complex128, int64, float64

def iterate(R: Callable[[complex], complex], z0: complex, max_iter: int):
    """
    Generates the orbit of z0 under the rational function R.
    Yields successive values until max_iter is reached or z escapes to infinity.
    """
    z = z0
    zn = [z0]
    
    for _ in range(max_iter):
        try:
            z = R(z)
            
            # Check for standard float infinity or NaN
            if math.isinf(z.real) or math.isnan(z.real):
                break
                
            zn.append(z)
            
        except (ZeroDivisionError, OverflowError):
            # Hit a pole exactly, or the float overflowed
            break
    
    return zn



# EXAMPLE FOR EFFICIENT ITERATION (generated by AI)

# Numba requires the function R to be JIT-compiled as well
@njit(complex128(complex128))
def R(z):
    return (z**2 + 1) / (z - 0.5)

@njit(int64(complex128, int64, float64))
def iterate_fast(z0, max_iter, escape_radius=1e10):
    # Pre-allocating an array is faster than appending if we know the max size
    # However, if you only need the *final* value or the *escape time*, 
    # you shouldn't store the array at all!
    
    z = z0
    for i in range(max_iter):
        # We must manually check denominator to avoid crashing the compiled C code
        if z == 0.5: 
            return i # Escaped at iteration i due to pole
            
        z = (z**2 + 1) / (z - 0.5)
        
        if abs(z) > escape_radius:
            return i # Returns the escape time
            
    return max_iter
